import { useEffect, useState } from 'react'
import { CheckCircle2, Printer, QrCode } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import type { FinishedGoodsLotLabel, OperatorProductionDetail, ProductionCompletionResult } from '@/features/operator-production/types'

function formatDate(value: string) { return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(value)) }

export function ProductionCompletionCard({ detail, isSubmitting, error, onComplete, onLoadLabel, onViewFg, onPrint, onBack }: { detail: OperatorProductionDetail; isSubmitting: boolean; error: string | null; onComplete: (actualOutput: number) => Promise<ProductionCompletionResult>; onLoadLabel: (id: string) => Promise<FinishedGoodsLotLabel>; onViewFg: (id: string) => void; onPrint: (id: string) => void; onBack: () => void }) {
  const [actualOutput, setActualOutput] = useState('')
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [result, setResult] = useState<ProductionCompletionResult | null>(null)
  const [label, setLabel] = useState<FinishedGoodsLotLabel | null>(null)
  const uom = detail.unitOfMeasureSymbol ?? detail.unitOfMeasureCode
  const parsed = Number(actualOutput.replace(',', '.'))
  const valid = Number.isFinite(parsed) && parsed > 0 && /^\d+(?:[.,]\d{1,4})?$/.test(actualOutput.trim())
  async function submit() { const next = await onComplete(parsed); setResult(next); setConfirmOpen(false) }
  useEffect(() => { if (result) void onLoadLabel(result.finishedGoodsLot.id).then(setLabel).catch(() => setLabel(null)) }, [onLoadLabel, result])
  if (result) return <CompletedProductionCard result={result} label={label} onViewFg={onViewFg} onPrint={onPrint} onBack={onBack} />
  return <Card className="border-signal/35"><CardContent className="space-y-6 p-6 sm:p-8"><div><div className="text-xs font-semibold uppercase tracking-[0.18em] text-signal">All steps completed</div><h2 className="mt-2 font-display text-3xl font-semibold text-ink">Production Summary</h2><p className="mt-2 text-sm text-slate-600">Review hasil produksi sebelum Finished Goods LOT dibuat oleh backend.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Summary label="Product" value={detail.productName} /><Summary label="PO Number" value={detail.productionOrderNumber} /><Summary label="Recipe Version" value={`V${detail.recipeVersionNumber}`} /><Summary label="Target Output" value={`${detail.targetOutput} ${uom}`} /><Summary label="Completed Steps" value={`${detail.progress.completedSteps}/${detail.progress.totalSteps}`} /><Summary label="Material Consumption" value={`${detail.materialConsumptionSummary.postedLineCount} LOT line · ${detail.materialConsumptionSummary.totalActualQuantity} actual`} /><Summary label="Deviations" value={`${detail.deviationSummary.totalCount} total · ${detail.deviationSummary.approvedCount} approved`} /></div><div><label className="text-sm font-semibold text-ink">Actual Output <span className="text-red-600">*</span></label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><Input inputMode="decimal" value={actualOutput} onChange={(event) => setActualOutput(event.target.value)} placeholder={`Contoh: ${detail.targetOutput}`} disabled={isSubmitting} /><span className="flex h-14 min-w-20 items-center justify-center rounded-2xl bg-sand/45 px-4 text-sm font-semibold text-ink">{uom}</span></div>{actualOutput && !valid ? <p className="mt-2 text-sm text-red-700">Actual Output harus angka lebih dari 0, maksimal 4 desimal.</p> : null}</div>{error ? <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}<Button size="lg" disabled={!valid || isSubmitting} onClick={() => setConfirmOpen(true)}>{isSubmitting ? 'Menyelesaikan...' : 'Complete Production'}</Button><Dialog open={confirmOpen} onOpenChange={(open) => !isSubmitting && setConfirmOpen(open)}><DialogContent><DialogHeader><DialogTitle>Complete Production?</DialogTitle><DialogDescription>Production akan diselesaikan dan Finished Goods LOT akan dibuat. Pastikan Actual Output sudah benar.</DialogDescription></DialogHeader><div className="rounded-xl bg-sand/45 p-4 text-sm">Actual Output: <b>{actualOutput} {uom}</b></div><DialogFooter><Button variant="secondary" disabled={isSubmitting} onClick={() => setConfirmOpen(false)}>Batal</Button><Button disabled={isSubmitting} onClick={() => void submit()}>{isSubmitting ? 'Memproses...' : 'Ya, Complete Production'}</Button></DialogFooter></DialogContent></Dialog></CardContent></Card>
}

function CompletedProductionCard({ result, label, onViewFg, onPrint, onBack }: { result: ProductionCompletionResult; label: FinishedGoodsLotLabel | null; onViewFg: (id: string) => void; onPrint: (id: string) => void; onBack: () => void }) { const fg = result.finishedGoodsLot; const uom = fg.unitOfMeasure.symbol ?? fg.unitOfMeasure.code; return <Card className="overflow-hidden border-emerald-200"><CardContent className="space-y-6 p-6 sm:p-8"><div className="flex gap-3"><CheckCircle2 className="text-emerald-600" size={32} /><div><div className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Production Completed</div><h2 className="mt-2 font-display text-3xl font-semibold text-ink">{fg.finishedGoodsLotNumber}</h2></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Summary label="Product" value={fg.productName} /><Summary label="Target Output" value={`${result.targetOutput} ${uom}`} /><Summary label="Actual Output" value={`${result.actualOutput} ${uom}`} /><Summary label="Yield" value={`${result.yieldValue}%`} /><Summary label="Production Date" value={formatDate(fg.productionDate)} /><Summary label="QC Status" value="WAITING QC" /><Summary label="Inventory Status" value="NOT AVAILABLE" /></div><div className="rounded-2xl border border-ink/10 p-5"><div className="flex items-center gap-2 font-semibold text-ink"><QrCode size={18} />QR Finished Goods</div>{label ? <img className="mt-4 h-44 w-44 rounded-xl border border-slate-100" src={`data:image/png;base64,${label.qrImageBase64}`} alt={`QR ${fg.finishedGoodsLotNumber}`} /> : null}<p className="mt-2 break-all text-sm text-slate-600">{fg.qrToken}</p></div><div className="flex flex-wrap gap-3"><Button onClick={() => onViewFg(fg.id)}>View Finished Goods</Button><Button variant="secondary" onClick={() => onPrint(fg.id)}><Printer size={16} />Print QR Label</Button><Button variant="secondary" onClick={onBack}>Back to Production</Button></div></CardContent></Card> }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-ink/8 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 font-semibold text-ink">{value}</div></div> }
