import type { TutorialDefinition } from '@/types/tutorial'

/**
 * Guided Production (Operator) — cara menjalankan eksekusi produksi terpandu.
 * Semua step kritikal (consume submit, complete) bertipe INFO: panduan saja,
 * tidak mengeksekusi transaksi. Total 8 steps (mirror backend catalog).
 */
export const guidedProductionTutorial: TutorialDefinition = {
  id: 'guided-production',
  title: 'Guided Production (Operator)',
  description: 'Menuntun operator menjalankan eksekusi produksi terpandu: antrean, kartu step, timer, konsumsi LOT, deviasi, dan penyelesaian.',
  category: 'production',
  requiredPermissions: ['production-orders.execute'],
  allowedRoles: ['OPERATOR', 'PRODUCTION_SUPERVISOR', 'ADMIN', 'SUPERADMIN'],
  steps: [
    {
      id: 'step-1-queue',
      stepNumber: 1,
      totalSteps: 8,
      title: 'Antrean Kerja Operator',
      instruction: 'Buka menu Production → My Production untuk melihat daftar Production Order yang ditugaskan kepada Anda.',
      type: 'INFO',
      route: '/operator/production',
      targetSelector: '[data-tour="operator-queue"]',
      placement: 'right',
    },
    {
      id: 'step-2-queue-row',
      stepNumber: 2,
      totalSteps: 8,
      title: 'Pilih Production Order',
      instruction: 'Pilih baris Production Order berstatus Released untuk membuka halaman panduan produksi.',
      type: 'INFO',
      route: '/operator/production',
      targetSelector: '[data-tour="operator-queue-row"]',
    },
    {
      id: 'step-3-step-card',
      stepNumber: 3,
      totalSteps: 8,
      title: 'Kartu Step Aktif',
      instruction: 'Kartu step menampilkan instruksi proses, urutan, dan status eksekusi. Ikuti sesuai urutan yang dibuka sistem.',
      type: 'INFO',
      targetSelector: '[data-tour="guided-step-card"]',
      targetFallback: '[data-tour="operator-queue"]',
    },
    {
      id: 'step-4-timer',
      stepNumber: 4,
      totalSteps: 8,
      title: 'Timer Step',
      instruction: 'Step bertipe timer menampilkan hitung mundur. Panduan saja — jalankan timer sesuai instruksi supervisor di lantai produksi.',
      type: 'INFO',
      targetSelector: '[data-tour="guided-timer"]',
      targetFallback: '[data-tour="operator-queue"]',
    },
    {
      id: 'step-5-consume',
      stepNumber: 5,
      totalSteps: 8,
      title: 'Form Konsumsi LOT',
      instruction: 'Form konsumsi mencatat LOT dan actual quantity per step. Tutorial hanya menunjuk form; pengisian dan submit dilakukan di luar tutorial.',
      type: 'INFO',
      targetSelector: '[data-tour="guided-consume-form"]',
      targetFallback: '[data-tour="operator-queue"]',
      critical: true,
    },
    {
      id: 'step-6-deviation',
      stepNumber: 6,
      totalSteps: 8,
      title: 'Kapan Mengajukan Deviasi',
      instruction: 'Jika actual di luar tolerance, ajukan deviation melalui tautan ini. Approval dilakukan supervisor di modul Deviation.',
      type: 'INFO',
      targetSelector: '[data-tour="guided-deviation-link"]',
      targetFallback: '[data-tour="operator-queue"]',
    },
    {
      id: 'step-7-complete',
      stepNumber: 7,
      totalSteps: 8,
      title: 'Penyelesaian Produksi',
      instruction: 'Panel penyelesaian menampilkan actual output, Finished Goods LOT, dan status QC. Tombol complete hanya ditunjuk — tidak dieksekusi tutorial.',
      type: 'INFO',
      targetSelector: '[data-tour="guided-complete-info"]',
      targetFallback: '[data-tour="operator-queue"]',
      critical: true,
    },
    {
      id: 'step-8-done',
      stepNumber: 8,
      totalSteps: 8,
      title: 'Tutorial Guided Production Selesai',
      instruction: 'Selamat! Anda memahami alur eksekusi terpandu. Lanjutkan ke tutorial Material Consumption untuk detail pencatatan LOT.',
      type: 'INFO',
      targetSelector: '[data-tour="operator-queue"]',
      targetFallback: '[data-tour="operator-queue"]',
    },
  ],
}
