import type { TutorialDefinition } from '@/types/tutorial'

export const inventoryTutorial: TutorialDefinition = {
  id: 'inventory',
  title: 'Stok Bahan Baku & Manajemen Inventory',
  description: 'Menuntun user memahami agregasi stok material, breakdown LOT, rekomendasi FEFO, dan pergerakan stok (Stock Movement).',
  category: 'warehouse',
  requiredPermissions: ['inventory.view'],
  steps: [
    {
      id: 'step-1-inventory-menu',
      stepNumber: 1,
      totalSteps: 7,
      title: 'Menu Inventory',
      instruction: 'Buka menu Warehouse → Inventory untuk memantau ketersediaan stok bahan baku di gudang.',
      type: 'INFO',
      route: '/inventory',
      targetSelector: '[data-tour="inventory-menu"]',
      placement: 'right',
    },
    {
      id: 'step-2-total-qty',
      stepNumber: 2,
      totalSteps: 7,
      title: 'Total Agregasi Stok Material',
      instruction: 'Nilai ini merupakan total keseluruhan akumulasi stok bahan baku dari seluruh LOT yang masih aktif.',
      type: 'INFO',
      route: '/inventory',
      targetSelector: '[data-tour="inventory-total-qty"]',
    },
    {
      id: 'step-3-lot-breakdown',
      stepNumber: 3,
      totalSteps: 7,
      title: 'Breakdown Stok per LOT',
      instruction: 'Klik atau buka breakdown untuk melihat distribusi sisa kuantitas stok pada masing-masing Internal LOT.',
      type: 'INFO',
      route: '/inventory',
      targetSelector: '[data-tour="inventory-lot-breakdown"]',
    },
    {
      id: 'step-4-warehouse-filter',
      stepNumber: 4,
      totalSteps: 7,
      title: 'Filter Lokasi Warehouse',
      instruction: 'Gunakan filter lokasi gudang untuk menyaring tampilan stok khusus pada warehouse tertentu.',
      type: 'INFO',
      route: '/inventory',
      targetSelector: '[data-tour="inventory-warehouse-filter"]',
    },
    {
      id: 'step-5-fefo-recommendation',
      stepNumber: 5,
      totalSteps: 7,
      title: 'Rekomendasi FEFO (First-Expired, First-Out)',
      instruction: 'Indikator Recommended LOT menampilkan LOT yang harus diprioritaskan terlebih dahulu untuk produksi berdasarkan tanggal kadaluarsa terdekat.',
      type: 'INFO',
      route: '/inventory',
      targetSelector: '[data-tour="inventory-fefo-recommendation"]',
    },
    {
      id: 'step-6-stock-movements',
      stepNumber: 6,
      totalSteps: 7,
      title: 'Riwayat Pergerakan Stok (Stock Movement)',
      instruction: 'Buka menu Stock Movements untuk audit mutasi stok penerimaan, pemakaian produksi, penyesuaian, dan pemindahan antar gudang.',
      type: 'INFO',
      route: '/stock-movements',
      targetSelector: '[data-tour="inventory-stock-movement"]',
    },
    {
      id: 'step-7-complete',
      stepNumber: 7,
      totalSteps: 7,
      title: 'Tutorial Inventory Selesai',
      instruction: 'Selamat! Anda telah memahami cara membaca data persediaan dan manajemen FEFO di MOSA.',
      type: 'INFO',
      route: '/inventory',
      targetSelector: '[data-tour="inventory-menu"]',
    },
  ],
}
