import type { TutorialDefinition } from '@/types/tutorial'

export const lotAndQrTutorial: TutorialDefinition = {
  id: 'lot-qr',
  title: 'Internal LOT & Label QR Code',
  description: 'Menuntun user memahami struktur Internal LOT, detail spesifikasi, cetak label QR, dan pemindaian scanner QR.',
  category: 'warehouse',
  requiredPermissions: ['lots.view'],
  allowedRoles: ['Warehouse', 'Admin', 'SuperAdmin', 'Supervisor'],
  steps: [
    {
      id: 'step-1-lot-menu',
      stepNumber: 1,
      totalSteps: 6,
      title: 'Buka Daftar Internal LOT',
      instruction: 'Internal LOT merupakan identifier utama keterlacakan (traceability) bahan baku dalam MOSA.',
      type: 'INFO',
      route: '/lots',
      targetSelector: '[data-tour="lot-internal-lot-col"]',
    },
    {
      id: 'step-2-lot-detail',
      stepNumber: 2,
      totalSteps: 6,
      title: 'Buka Detail LOT',
      instruction: 'Klik pada salah satu Internal LOT untuk melihat data material, supplier, lokasi warehouse, sisa stok, dan tanggal expired.',
      type: 'INFO',
      route: '/lots',
      targetSelector: '[data-tour="lot-item-row"]',
    },
    {
      id: 'step-3-qr-representation',
      stepNumber: 3,
      totalSteps: 6,
      title: 'Visualisasi Kode QR',
      instruction: 'Setiap Internal LOT memiliki QR unik yang merepresentasikan identitas bahan baku tersebut secara tepat.',
      type: 'INFO',
      targetSelector: '[data-tour="lot-qr-code"]',
    },
    {
      id: 'step-4-print-label',
      stepNumber: 4,
      totalSteps: 6,
      title: 'Cetak Label QR',
      instruction: 'Gunakan tombol Print Label untuk mencetak stiker QR dan menempelkannya langsung pada kemasan fisik material di gudang.',
      type: 'INFO',
      targetSelector: '[data-tour="lot-print-label-btn"]',
    },
    {
      id: 'step-5-scan-qr',
      stepNumber: 5,
      totalSteps: 6,
      title: 'Pindai QR dengan Scanner',
      instruction: 'Gunakan fitur Scan QR pada perangkat tablet/mobile untuk memindai label fisik dan membuka informasi LOT secara instan.',
      type: 'INFO',
      route: '/lots',
      targetSelector: '[data-tour="lot-scan-qr-btn"]',
    },
    {
      id: 'step-6-complete',
      stepNumber: 6,
      totalSteps: 6,
      title: 'Tutorial LOT & QR Selesai',
      instruction: 'Anda telah memahami cara kerja pelabelan dan pemindaian LOT dalam sistem operasional MOSA.',
      type: 'INFO',
      route: '/lots',
      targetSelector: '[data-tour="lot-internal-lot-col"]',
    },
  ],
}
