import type { TutorialDefinition } from '@/types/tutorial'

export const productionOrderTutorial: TutorialDefinition = {
  id: 'production-order',
  title: 'Production Order & Material Requirement Check',
  description: 'Menuntun Production Supervisor merencanakan perintah produksi, memeriksa kecukupan stok bahan, hingga merilis order ke lapangan.',
  category: 'production',
  requiredPermissions: ['production-orders.view', 'production-orders.create'],
  allowedRoles: ['Production Supervisor', 'Admin', 'SuperAdmin'],
  steps: [
    {
      id: 'step-1-po-menu',
      stepNumber: 1,
      totalSteps: 16,
      title: 'Buka Production Orders',
      instruction: 'Buka menu Production → Production Orders untuk melihat dan merencanakan order produksi.',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-menu"]',
      placement: 'right',
    },
    {
      id: 'step-2-create-po-btn',
      stepNumber: 2,
      totalSteps: 16,
      title: 'Buat Production Order Baru',
      instruction: 'Klik tombol Create Production Order untuk mulai merencanakan jadwal batch produksi baru.',
      type: 'ACTION',
      route: '/production/orders',
      targetSelector: '[data-tour="po-create-btn"]',
      requiredAction: {
        type: 'click',
        elementSelector: '[data-tour="po-create-btn"]',
      },
    },
    {
      id: 'step-3-select-product',
      stepNumber: 3,
      totalSteps: 16,
      title: 'Pilih Produk Yang Akan Diproduksi',
      instruction: 'Pilih Product target yang akan diproduksi dalam batch ini.',
      type: 'ACTION',
      route: '/production/orders/create',
      targetSelector: '[data-tour="po-product-select"]',
      requiredAction: {
        type: 'select',
        elementSelector: '[data-tour="po-product-select"]',
        validate: () => {
          const el = document.querySelector<HTMLSelectElement>('[data-tour="po-product-select"]')
          return Boolean(el && el.value.trim().length > 0)
        },
      },
    },
    {
      id: 'step-4-approved-recipe',
      stepNumber: 4,
      totalSteps: 16,
      title: 'Pilih Resep Terverifikasi (Approved Recipe)',
      instruction: 'Production Order hanya dapat menggunakan Recipe yang telah berstatus Approved/Active.',
      type: 'ACTION',
      route: '/production/orders/create',
      targetSelector: '[data-tour="po-recipe-select"]',
      requiredAction: {
        type: 'select',
        elementSelector: '[data-tour="po-recipe-select"]',
        validate: () => {
          const el = document.querySelector<HTMLSelectElement>('[data-tour="po-recipe-select"]')
          return Boolean(el && el.value.trim().length > 0)
        },
      },
    },
    {
      id: 'step-5-target-output',
      stepNumber: 5,
      totalSteps: 16,
      title: 'Target Output Produksi',
      instruction: 'Masukkan jumlah total output produksi yang direncanakan untuk batch ini.',
      type: 'ACTION',
      route: '/production/orders/create',
      targetSelector: '[data-tour="po-target-output"]',
      requiredAction: {
        type: 'input',
        elementSelector: '[data-tour="po-target-output"]',
        validate: () => {
          const el = document.querySelector<HTMLInputElement>('[data-tour="po-target-output"]')
          return Boolean(el && Number(el.value) > 0)
        },
      },
    },
    {
      id: 'step-6-warehouse-source',
      stepNumber: 6,
      totalSteps: 16,
      title: 'Warehouse Sumber Bahan',
      instruction: 'Pilih gudang asal pengambilan bahan baku yang akan dipakai selama produksi.',
      type: 'ACTION',
      route: '/production/orders/create',
      targetSelector: '[data-tour="po-warehouse-select"]',
      requiredAction: {
        type: 'select',
        elementSelector: '[data-tour="po-warehouse-select"]',
        validate: () => {
          const el = document.querySelector<HTMLSelectElement>('[data-tour="po-warehouse-select"]')
          return Boolean(el && el.value.trim().length > 0)
        },
      },
    },
    {
      id: 'step-7-recipe-scaling',
      stepNumber: 7,
      totalSteps: 16,
      title: 'Kalkulasi Otomatis (Recipe Scaling)',
      instruction: 'MOSA secara otomatis menghitung kebutuhan tiap bahan baku berdasarkan rasio Standard Output Recipe dan Target Production yang diinput.',
      type: 'INFO',
      route: '/production/orders/create',
      targetSelector: '[data-tour="po-scaling-info"]',
    },
    {
      id: 'step-8-material-reqs',
      stepNumber: 8,
      totalSteps: 16,
      title: 'Tabel Kebutuhan Bahan (Material Requirements)',
      instruction: 'Bagian ini menampilkan rincian nama bahan baku, target kuantitas yang dibutuhkan, serta ketersediaan stok fisik di gudang.',
      type: 'INFO',
      route: '/production/orders/create',
      targetSelector: '[data-tour="po-material-requirements"]',
    },
    {
      id: 'step-9-save-draft',
      stepNumber: 9,
      totalSteps: 16,
      title: 'Simpan Draft Production Order',
      instruction: 'Simpan order sebagai Draft agar rencana jadwal produksi tersimpan di sistem.',
      type: 'INFO',
      route: '/production/orders/create',
      targetSelector: '[data-tour="po-save-draft-btn"]',
    },
    {
      id: 'step-10-check-material',
      stepNumber: 10,
      totalSteps: 16,
      title: 'Verifikasi Ketersediaan Stok (Check Material)',
      instruction: 'Buka detail order lalu klik Check Material untuk membandingkan total kebutuhan produksi dengan stok Internal LOT aktif berdasarkan aturan FEFO.',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-check-material-btn"]',
      targetFallback: '[data-tour="po-menu"]',
    },
    {
      id: 'step-11-ready-condition',
      stepNumber: 11,
      totalSteps: 16,
      title: 'Kondisi Stok Cukup (READY)',
      instruction: 'Di halaman detail order: jika semua stok bahan baku mencukupi, status order berubah menjadi READY dan dapat dilanjutkan ke tahap Release.',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-status-badge"]',
      targetFallback: '[data-tour="po-menu"]',
    },
    {
      id: 'step-12-shortage-condition',
      stepNumber: 12,
      totalSteps: 16,
      title: 'Kondisi Defisit Stok (MATERIAL SHORTAGE)',
      instruction: 'Di halaman detail order: jika salah satu bahan baku tidak mencukupi, sistem menampilkan peringatan MATERIAL SHORTAGE dan mencegah Release hingga stok dilengkapi melalui Goods Receiving.',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-status-badge"]',
      targetFallback: '[data-tour="po-menu"]',
    },
    {
      id: 'step-13-release-po',
      stepNumber: 13,
      totalSteps: 16,
      title: 'Rilis Production Order (Release)',
      instruction: 'Di halaman detail order: jika status READY, klik Release agar instruksi kerja tersedia bagi Operator. Panduan saja — jangan rilis order nyata saat tutorial.',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-release-btn"]',
      targetFallback: '[data-tour="po-menu"]',
      critical: true,
    },
    {
      id: 'step-14-released-status',
      stepNumber: 14,
      totalSteps: 16,
      title: 'Status Order RELEASED',
      instruction: 'Setelah rilis, Production Order berstatus RELEASED dan siap dieksekusi di lini produksi (Guided Production).',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-status-badge"]',
      targetFallback: '[data-tour="po-menu"]',
    },
    {
      id: 'step-15-summary',
      stepNumber: 15,
      totalSteps: 16,
      title: 'Review Rencana Order',
      instruction: 'Periksa kembali jadwal dan alokasi operator sebelum proses penimbangan dimulai oleh lini operasional.',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-menu"]',
    },
    {
      id: 'step-16-complete',
      stepNumber: 16,
      totalSteps: 16,
      title: 'Tutorial Production Order Selesai',
      instruction: 'Selamat! Anda telah memahami seluruh alur perencanaan dan rilis Production Order di MOSA.',
      type: 'INFO',
      route: '/production/orders',
      targetSelector: '[data-tour="po-menu"]',
    },
  ],
}
