import type { TutorialDefinition } from '@/types/tutorial'

export const recipeBuilderTutorial: TutorialDefinition = {
  id: 'recipe-builder',
  title: 'Recipe Builder & Approval Workflow',
  description: 'Menuntun Production Supervisor menyusun resep formulasi produksi dari draft sampai disetujui (Approved).',
  category: 'production',
  requiredPermissions: ['recipes.view'],
  allowedRoles: ['Production Supervisor', 'Admin', 'SuperAdmin'],
  steps: [
    {
      id: 'step-1-recipe-menu',
      stepNumber: 1,
      totalSteps: 13,
      title: 'Buka Menu Recipe',
      instruction: 'Buka menu Production → Recipes untuk mengelola daftar resep formulasi produk.',
      type: 'INFO',
      route: '/production/recipes',
      targetSelector: '[data-tour="recipe-menu"]',
      placement: 'right',
    },
    {
      id: 'step-2-create-recipe-btn',
      stepNumber: 2,
      totalSteps: 13,
      title: 'Buat Resep Baru',
      instruction: 'Klik tombol Create Recipe untuk membuka formulir penyusunan resep baru.',
      type: 'ACTION',
      route: '/production/recipes',
      targetSelector: '[data-tour="recipe-create-btn"]',
      requiredAction: {
        type: 'click',
        elementSelector: '[data-tour="recipe-create-btn"]',
      },
    },
    {
      id: 'step-3-select-product',
      stepNumber: 3,
      totalSteps: 13,
      title: 'Pilih Produk Target',
      instruction: 'Pilih Product yang akan dibuatkan formulasi resepnya.',
      type: 'ACTION',
      route: '/production/recipes/create',
      targetSelector: '[data-tour="recipe-product-select"]',
      requiredAction: {
        type: 'select',
        elementSelector: '[data-tour="recipe-product-select"]',
        validate: () => {
          const el = document.querySelector<HTMLSelectElement>('[data-tour="recipe-product-select"]')
          return Boolean(el && el.value.trim().length > 0)
        },
      },
    },
    {
      id: 'step-4-std-output',
      stepNumber: 4,
      totalSteps: 13,
      title: 'Standard Output Recipe',
      instruction: 'Tentukan jumlah keluaran standar (Standard Output) resep ini. Nilai ini menjadi basis kalkulasi Recipe Scaling saat Production Order dibuat.',
      type: 'ACTION',
      route: '/production/recipes/create',
      targetSelector: '[data-tour="recipe-std-output"]',
      requiredAction: {
        type: 'input',
        elementSelector: '[data-tour="recipe-std-output"]',
        validate: () => {
          const el = document.querySelector<HTMLInputElement>('[data-tour="recipe-std-output"]')
          return Boolean(el && Number(el.value) > 0)
        },
      },
    },
    {
      id: 'step-5-add-step',
      stepNumber: 5,
      totalSteps: 13,
      title: 'Tambah Langkah Proses (Add Step)',
      instruction: 'Klik Add Step untuk menambahkan instruksi langkah produksi secara berurutan.',
      type: 'ACTION',
      route: '/production/recipes/create',
      targetSelector: '[data-tour="recipe-add-step-btn"]',
      requiredAction: {
        type: 'click',
        elementSelector: '[data-tour="recipe-add-step-btn"]',
      },
    },
    {
      id: 'step-6-step-types',
      stepNumber: 6,
      totalSteps: 13,
      title: 'Tipe Langkah Produksi',
      instruction: 'Pilih tipe langkah: Material (pengambilan bahan), Process (pencampuran/pengolahan), Timer (pemanasan/reaksi), atau Check (pemeriksaan QC).',
      type: 'INFO',
      route: '/production/recipes/create',
      targetSelector: '[data-tour="recipe-step-type-select"]',
    },
    {
      id: 'step-7-material-fields',
      stepNumber: 7,
      totalSteps: 13,
      title: 'Rincian Material & Toleransi',
      instruction: 'Untuk langkah Material, tentukan Raw Material, Target Quantity, Satuan (UOM), dan batas toleransi persentase akurasi penimbangan.',
      type: 'INFO',
      route: '/production/recipes/create',
      targetSelector: '[data-tour="recipe-material-step-fields"]',
    },
    {
      id: 'step-8-step-sequence',
      stepNumber: 8,
      totalSteps: 13,
      title: 'Urutan Eksekusi (Sequence)',
      instruction: 'Urutan langkah ini nantinya menjadi petunjuk wajib yang harus diikuti Operator saat eksekusi Guided Production.',
      type: 'INFO',
      route: '/production/recipes/create',
      targetSelector: '[data-tour="recipe-step-sequence"]',
    },
    {
      id: 'step-9-submit-approval',
      stepNumber: 9,
      totalSteps: 13,
      title: 'Submit for Approval',
      instruction: 'Setelah resep lengkap, klik Submit for Approval untuk mengajukan verifikasi ke supervisor/manajer.',
      type: 'INFO',
      route: '/production/recipes/create',
      targetSelector: '[data-tour="recipe-submit-approval-btn"]',
    },
    {
      id: 'step-10-approval-queue',
      stepNumber: 10,
      totalSteps: 13,
      title: 'Antrean Persetujuan Resep',
      instruction: 'Pengguna yang memiliki permission approval dapat meninjau resep pada halaman Recipe Approval Queue.',
      type: 'INFO',
      route: '/production/recipes/approval-queue',
      targetSelector: '[data-tour="recipe-approve-btn"]',
    },
    {
      id: 'step-11-approve-action',
      stepNumber: 11,
      totalSteps: 13,
      title: 'Approve Recipe',
      instruction: 'Klik Approve untuk mengesahkan resep yang telah diperiksa kebenaran komposisinya.',
      type: 'INFO',
      route: '/production/recipes/approval-queue',
      targetSelector: '[data-tour="recipe-approve-btn"]',
    },
    {
      id: 'step-12-active-badge',
      stepNumber: 12,
      totalSteps: 13,
      title: 'Status APPROVED / ACTIVE',
      instruction: 'Resep yang berstatus Approved/Active kini siap digunakan untuk rilis Production Order.',
      type: 'INFO',
      route: '/production/recipes',
      targetSelector: '[data-tour="recipe-active-badge"]',
    },
    {
      id: 'step-13-complete',
      stepNumber: 13,
      totalSteps: 13,
      title: 'Tutorial Recipe Builder Selesai',
      instruction: 'Selamat! Anda telah menguasai alur pembuatan dan pengesahan resep produksi.',
      type: 'INFO',
      route: '/production/recipes',
      targetSelector: '[data-tour="recipe-menu"]',
    },
  ],
}
